### ISSUE TITLE
Link doesn't work?

### ISSUE THREAD

**Issue by kernelism** [ReaVNaiL/LeetCode-Assistant#100]
is it invitable or should I locally set it up and invite?

**Comment by NineTailSecurity** [comment]
Haven't touched this project in a while, but if I remember correctly it should be run local and invited.

**Comment by MinatoNamikaze02** [comment]
Thank you!

**Comment by ReaVNaiL** [comment]
> is it invitable or should I locally set it up and invite?

It used to be invited, however it's no longer running. I might be able to host it and allow invites again.

**Comment by kernelism** [comment]
> > is it invitable or should I locally set it up and invite?
> 
> It used to be invited, however it's no longer running. I might be able to host it and allow invites again.

Hi it's okay, I think I could set it up myself. If you're planning to host it anyway, let me know.

**Comment by ReaVNaiL** [comment]
> > > is it invitable or should I locally set it up and invite?
> > 
> > 
> > It used to be invited, however it's no longer running. I might be able to host it and allow invites again.
> 
> Hi it's okay, I think I could set it up myself. If you're planning to host it anyway, let me know.

It was a project that was left out in the dust when heroku stopped providing the free tier lol, I'm going to host it soon, and soon as I do will let you know!
